### ISSUE TITLE
Feature : Fetch Speaker Details from GitHub API

### ISSUE THREAD

**Issue by Safnaj** [gcsrilanka/openhackday-lk#62]
Problem : 
If the speaker changed his GitHub Avatar, current URL wont work.

Solution : 
Can use GitHub API to fetch user details such as Name & Image from speaker GitHub Username.

GitHub Profile URL available in below location : 
https://github.com/GitHubExperts-LK/openhackday-lk/blob/main/src/data/speakers.json

**Comment by nimeshkavinda** [comment]
@Safnaj Hi so i started working on this just now. but I ran into this issue where i reach some sort of a request limit implemented by github after sending couple of requests. Wondering if this requires authentication in which case will have to setup secret keys as well right? below is the 403 err response i get

`{
    "message": "API rate limit exceeded for 111.223.158.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}`

<img width="1440" alt="Screenshot 2021-10-30 at 8 39 36 PM" src="https://user-images.githubusercontent.com/44240093/139538836-c502912a-9f5d-4c31-8ebd-2eaf74068e0f.png">

**Comment by Safnaj** [comment]
> "API rate limit exceeded for 111.223.158.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more detail

Yes, GitHub API Call is limited to 60 per hour. If we can have an token_code to authenticate the API it wont be an issue.

`curl "https://api.github.com/repos/user/repo/issues?state=closed&access_token=token"`

@Shehanka can u create and share an access_token with him ?

**Comment by nimeshkavinda** [comment]
> > "API rate limit exceeded for 111.223.158.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more detail
> 
> Yes, GitHub API Call is limited to 60 per hour. If we can have an token_code to authenticate the API it wont be an issue.
> 
> `curl "https://api.github.com/repos/user/repo/issues?state=closed&access_token=token"`
> 
> @Shehanka can u create and share an access_token with him ?

Okay thanks

**Comment by Safnaj** [comment]
@nimeshkavinda are u working on this ??

**Comment by Safnaj** [comment]
> > "API rate limit exceeded for 111.223.158.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more detail
> 
> Yes, GitHub API Call is limited to 60 per hour. If we can have an token_code to authenticate the API it wont be an issue.
> 
> `curl "https://api.github.com/repos/user/repo/issues?state=closed&access_token=token"`
> 
> @Shehanka can u create and share an access_token with him ?

@Shehanka Reminder !!!

**Comment by Shehanka** [comment]
> > > "API rate limit exceeded for 111.223.158.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more detail
> > 
> > 
> > Yes, GitHub API Call is limited to 60 per hour. If we can have an token_code to authenticate the API it wont be an issue.
> > `curl "https://api.github.com/repos/user/repo/issues?state=closed&access_token=token"`
> > @Shehanka can u create and share an access_token with him ?
> 
> @Shehanka Reminder !!!

there is a problem giving him a token. even if I create a token only with read access. he will be able to see all of work repos as well. I don't think sharing a PAT would be good idea
